key_sub = {
        'Key.enter': '[ENTER]', 
        'Key.backspace': '[BACKSPACE]', 
        'Key.space': '[SPACE]',
	    'Key.alt_l': '[LEFT ALT]', 
        'Key.alt_gr': '[RIGHT ALT]', 
        'Key.tab': '[TAB]', 
        'Key.delete': '[DEL]',
        'Key.ctrl_l': '[LEFT CTRL]', 
        'Key.ctrl_r': '[RIGHT CTRL]', 
        'Key.left': '[LEFT ARROW]', 
        'Key.right': '[RIGHT ARROW]',  
        'Key.up': '[UP ARROW]', 
        'Key.down': '[DOWN ARROW]',
        'Key.shift':'[LEFT SHIFT]', 
        'Key.shift_r': '[RIGHT SHIFT]', 
        'Key.esc': '[ESCAPE]',
        'Key.caps_lock': '[CAPS LOCK]',
        'Key.cmd': '[WINDOWS KEY]',
        'Key.print_screen': '[PRNT SCR]', 
        'Key.end': '[END]',
        'Key.home': '[HOME]', 
        'Key.page_down': '[PAGE DOWN]', 
        'Key.page_up': '[PAGE UP]', 
        '\\x13': '[CTRL-S]', 
        '\\x17': '[CTRL-W]', 
        '\\x01': '[CTRL-A]', 
        '\\x03': '[CTRL-C]', 
        '\\x16': '[CTRL-V]',
        '\\x10': '[CTRL-P]',
        '\\x12': '[CTRL-R]',
        '\\x14': '[CTRL-T]'
        }